name: Comment when issue closed
run-name: Adding comment on issue ${{ github.event.issue.number }} closed
on:
  issues:
    types:
      - closed
permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment
        run: gh issue comment "$ISSUE" --repo "$GITHUB_REPOSITORY" --body "This issue has been closed!"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE: ${{ github.event.issue.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
