name: Comment when opened
on:
  issues:
    types:
      - opened
permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GH CLI
        run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Add Comment
        run: gh issue comment "$ISSUE" --body "Thank you for opening this issue!"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE: ${{ github.event.issue.number }}
